### ISSUE TITLE
Out of Place Content

### ISSUE THREAD

**Issue by liveactionllama** [code-423n4/docs#11]
Within the _Estimating Likelihood_ > _[Opportunity](https://docs.code4rena.com/roles/wardens/judging-criteria#opportunity)_ section of the **Judging Criteria** document, the 4th bullet seems to have some out of place content inserted. I believe it should instead say something like "No access or resources required (9)" or something like that.

**Comment by CloudEllie** [comment]
Assigning this back to you - want to set up a PR for this?

**Comment by liveactionllama** [comment]
@CloudEllie - I created a PR for this (https://github.com/code-423n4/code423n4.com/pull/1061). Related to Section 6.3, bullet 4 - I corrected to "No access or resources required (9)". I guessed on the score of 9, so please double-check me on that. TY!

**Comment by liveactionllama** [comment]
UPDATE: @CloudEllie - Mango happened to notice my PR and approved it, so there's actually nothing for you to do there. As long as my update was correct, specifically the score of 9?
![image](https://user-images.githubusercontent.com/98446738/153976232-f415bfac-73e9-4b4a-a84e-b9640dbe6f77.png)

**Comment by liveactionllama** [comment]
Discovered the content I was updating in GH is old and isn't actually tied to the website (so my PR didn't change the site). Ellie provided the link to the current content (https://github.com/code-423n4/docs/blob/main/roles/wardens/judging-criteria.md). Awaiting clarification from her regarding whether the score of 9 is correct on this, then I'll proceed with the update.

**Comment by liveactionllama** [comment]
Per discussion with Ellie, the page history doesn't clear up what the score should be; however, the page references the OWASP standards, and those clarify that (9) is correct. https://owasp.org/www-community/OWASP_Risk_Rating_Methodology

**Comment by liveactionllama** [comment]
Corrected. Verified update appearing on C4 website.
https://docs.code4rena.com/roles/wardens/judging-criteria#opportunity
